version: '2'
services:
  vv-server:
    build: .
    tty: true
  nginx-server:
    image: nginx
    volumes:
     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
  docservice:
    image: onlyoffice/4testing-documentserver-ie:5.1.99.673
    volumes:
    - ./plugin:/var/www/onlyoffice/documentserver/sdkjs-plugins/plugin
